import numpy as np
import matplotlib.pyplot as plt
import matplotlib
import sys
matplotlib.rc('text', usetex = True)
matplotlib.rc('font', **{'family':'sans-serif', 'sans-serif':['Computer Modern Roman, Times']})

# Welcome to Wien2k Plotter (W2kPlotter) a python class for plotting the bandstructure and density of states from WIEN2k's output files.


# Design to be an interactive program that allows the user to communicte their needs to the code and the code produces publishable figures.
# All the user must do is provide the correct input files into the program.
class W2kPlotter():

    def __init__(self):
        # the grace file will give us the high symmetry points because as of now I'm
        # not sure how to find the high symmetry points
        self.spaghetti = spaghetti
        self.grace = grace
        self.save = save
        self.Emin = Emin
        self.Emax = Emax
        self.title = title

    def getHighSymmetryPoints(self, grace):
        f = open(grace, 'r')
        highSymmPts = []
        highSymmLabels = []
        for i, line in enumerate(f):
            if 'tick major' in line:
                if 'grid on' not in line:
                    line = line.lstrip().rstrip()
                    pt = float(line.split()[5])
                    highSymmPts.append(pt)
            if 'ticklabel' in line:
                if 'size' not in line:
                    line = line.lstrip().rstrip()
                    label = line.split()[4][2:]
                    if label == '\\xG"':
                        highSymmLabels.append(r'$\Gamma$')
                    else:
                        highSymmLabels.append(label)
        return(highSymmPts, highSymmLabels)


    def BS_Plotter(self, spaghetti, grace, title, save, Emin, Emax):
        f = open(spaghetti, 'r')
        k = []
        E = []
        highsymmpts, labels = self.getHighSymmetryPoints(grace)

        plt.figure()
        for i, line in enumerate(f):
            if 'bandindex' not in line:
                line = line.rstrip().lstrip()
                if float(line.split()[4]) > Emin and float(line.split()[4]) < Emax:
                    k.append(float(line.split()[3]))
                    E.append(float(line.split()[4]))

            else:
                plt.plot(k, E, linewidth = 1)
                kmax = np.max(k)
                k = []
                E = []
        plt.grid(True, linewidth =1, linestyle =':')
        # This part will be generated by another function at antoher point
        #plt.xticks(highsymmpts, (r'$\Gamma$', 'X', 'M', r'$\Gamma$', 'Z', 'R', 'A', 'Z'))
        plt.xticks(highsymmpts, labels)
        plt.ylabel('Energy (eV)')
        plt.ylim([Emin, Emax])
        plt.xlim([0,kmax])

        plt.plot(np.linspace(0,kmax,1000), [0 for i in range(1000)], 'k--', linewidth = 1)
        plt.title(title)
        if self.save:
            plt.savefig('%s.eps'  %(title), format = 'eps')
        else:
            plt.show()

    def DOS_Plotter(self, dosfiles, title, save, Emin, Emax):

        def getData(file):
            energies = []
            dz2 = []
            dxy = []
            dx2y2 = []
            dxzdyz = []
            with open(file) as f:
               for i, line in enumerate(f):
                    if i>2:
                        if 'dn' in file:
                            line = line.lstrip().rstrip()
                            energies.append(float(line.split()[0]))
                            dz2.append((-1)*float(line.split()[1]))
                            dxy.append((-1)*float(line.split()[2]))
                            dx2y2.append((-1)*float(line.split()[3]))
                            dxzdyz.append((-1)*float(line.split()[4]))
                        else:
                            line = line.lstrip().rstrip()
                            energies.append(float(line.split()[0]))
                            dz2.append(float(line.split()[1]))
                            dxy.append(float(line.split()[2]))
                            dx2y2.append(float(line.split()[3]))
                            dxzdyz.append(float(line.split()[4]))
            return energies, dz2, dxy, dx2y2, dxzdy
            
