import numpy as np
import matplotlib.pyplot as plt
import matplotlib
import sys
matplotlib.rc('text', usetex = True)
matplotlib.rc('font', **{'family':'sans-serif', 'sans-serif':['Computer Modern Roman, Times']})

# Welcome to Wien2k Plotter (W2kPlotter) a python class for plotting the bandstructure and density of states from WIEN2k's output files.


# Design to be an interactive program that allows the user to communicte their needs to the code and the code produces publishable figures.
# All the user must do is provide the correct input files into the program.
class W2kPlotter():

    def getHighSymmetryPoints(self, grace):
        f = open(grace, 'r')
        highSymmPts = []
        highSymmLabels = []
        for i, line in enumerate(f):
            if 'tick major' in line:
                if 'grid on' not in line:
                    line = line.lstrip().rstrip()
                    pt = float(line.split()[5])
                    highSymmPts.append(pt)
            if 'ticklabel' in line:
                if 'size' not in line:
                    line = line.lstrip().rstrip()
                    label = line.split()[4][2:]
                    if label == '\\xG"':
                        highSymmLabels.append(r'$\Gamma$')
                    else:
                        highSymmLabels.append(label)
        return(highSymmPts, highSymmLabels)


    def BS_Plotter(self, spaghetti, grace, title, save, Emin, Emax):
        f = open(spaghetti, 'r')
        k = []
        E = []
        highsymmpts, labels = self.getHighSymmetryPoints(grace)

        plt.figure()

        for i, line in enumerate(f):
            if 'bandindex' not in line:
                line = line.rstrip().lstrip()
                if float(line.split()[4]) > Emin and float(line.split()[4]) < Emax:
                    k.append(float(line.split()[3]))
                    E.append(float(line.split()[4]))

            else:
                # need for program to grab the list k value because this will be the plot range
                plt.plot(k, E, linewidth=2)
                k = []
                E = []
        plt.grid(True, linewidth =1, linestyle =':')
        # This part will be generated by another function at antoher point
        #plt.xticks(highsymmpts, (r'$\Gamma$', 'X', 'M', r'$\Gamma$', 'Z', 'R', 'A', 'Z'))
        plt.xticks(highsymmpts, labels)
        plt.ylabel('Energy (eV)')
        plt.ylim([Emin, Emax])
        plt.xlim([0,2.90982])

        plt.plot(np.linspace(0,2.90982,1000), [0 for i in range(1000)], 'k--', linewidth = 1)
        plt.title(title)
        if save:
            filename = input('Please enter a file name:\n')
            form = input('Please enter a file name format:\n')
            plt.savefig('%s.%s'  %(filename, form), format = form)
        else:
            plt.show()

    def DOS_Plooter(self, dosfiles, title, save, Emin, Emax ):
        for file in dosfiles:
            with open(file) as f:
                energy = []
                masterlist = []
                for i, line in enumerate:
                    if i > 2:
                        if 'dn' in file:
                            line = line.strip().rstrip()
                            energy.append(float(line[0]))
    # def DOS_Plotter(self, dosfiles, title, save, Emin, Emax):
    #
    #     for file in dosfiles:
    #         # Sometimes you will need to provide a list of dos files
    #         with open(file) as f:
    #             for i, line in enumerate(f):
    #                 if i>2:
    #                     if 'dn' in file:
    #                         line = line.lstrip().rstrip()
    #                         for li in line:
    #                             # Need a clever way to take in the input
    #
    #                     else:
    #                         line = line.lstrip().rstrip()
